### ISSUE TITLE
NCR Safe Server Status does not appear to work

### ISSUE THREAD

**Issue by untuned** [e-im/FreedomChat#14]
I've recently updated FreedomChat to 1.2.1, and updated the config to set everything to `true`, then restarted. However, it doesn't seem that the "Safe" status is showing up on the client.

Client: Fabulously Optimized 4.4.4 for 1.19.2

Server:
```
Current: git-Purpur-1832 (MC: 1.19.2)*
Previous: git-Purpur-1799 (MC: 1.19.2)
* You are running the latest version
```

EDIT: Ok it suddenly started working? ![example](https://untnd.me/F5M-m5Z3Z)

**Comment by e-im** [comment]
do you have `enforce-secure-profiles` set to `false` in `server.properties`? That is required for the secure status in the chat window.

it'll show on the server list screen even without that.

**Comment by untuned** [comment]
> do you have `enforce-secure-profiles` set to `false` in `server.properties`? That is required for the secure status in the chat window.
> 
> it'll show on the server list screen even without that.

I had that set to false, yes. Checked that before submitting the issue.

**Comment by e-im** [comment]
I've looked into this and can't replicate or see how it could possibly happen. Given it's started working for you, I'll close this. If you have any future problems with this feature, please leave a comment.
