### ISSUE TITLE
Hi there just a small question

### ISSUE THREAD

**Issue by TuckerAndrews3** [e-im/FreedomChat#15]
How can I tell if the plugin is working? It is green on startup, so all is well there. I can click the Player Reporting button, but then it will say "No reportable messages from this player", so I assume that it's working? I have chat-previews set to false

**Comment by e-im** [comment]
On a vanilla client, all sent messages will have a light gray bar to the left of them if the plugin is working. However, just checking the report is the easiest way. If nothing is reportable, it is working.

The plugin is meant to be as unobtrusive as possible, so nothing is logged/etc.

**Comment by TuckerAndrews3** [comment]
I have to tell you. This plugin is extremely well made and professional, hats off to you my friend. I am seeing the gray bar, so I suppose that tells us it's working all good!

**Comment by e-im** [comment]
Glad its working well for you.
