### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by e-im** [e-im/FreedomChat#20]
This plugin won't work on 1.19.3 for the moment. This is a known issue and will be resolved in ~8 hours, or whenever Paper releases for 1.19.3. whichever comes later

**Comment by AlphaTimes234** [comment]
Will this plugin support anti telemetry?

**Comment by e-im** [comment]
No. This is a plugin that disables chat reporting, anything else is out of scope.

Beyond that, telemetry collected by Mojang on the server-side is practically nonexistent. Paper and many plugins you may install collect their own, more detailed usage data. This can (for the most part) be disabled by disabling bStats (see `plugins/bStats/config.yml`).

**Comment by AlphaTimes234** [comment]
> No. This is a plugin that disables chat reporting, anything else is out of scope.
> 
> Beyond that, telemetry collected by Mojang on the server-side is practically nonexistent. Paper and many plugins you may install collect their own, more detailed usage data. This can (for the most part) be disabled by disabling bStats (see `plugins/bStats/config.yml`).

Thank you
