### ISSUE TITLE
Toast appears on 1.19.3

### ISSUE THREAD

**Issue by Bobcat00** [e-im/FreedomChat#21]
With FreedomChat 1.3.0, the toast still appears when joining 1.19.3.

FreedomChat version 1.3.0
git-Paper-315 (MC: 1.19.3)

Config:
```
rewrite-chat: true
claim-secure-chat-enforced: true
send-prevents-chat-reports-to-client: false
```

server.properties:
```
enforce-secure-profile=false
```

**Comment by e-im** [comment]
Sorry about that. I think see the issue, but unfortunately can't verify or push a fix now. I'll do this tonight (~6hrs), though.

**Comment by Bobcat00** [comment]
Hey, no problem. Just wanted to let you know.

**Comment by e-im** [comment]
Should be resolved in 9e58cde2d95d6c472eb28f93c7acb1063e069964

**Comment by e-im** [comment]
Sorry, I missed your last comment. Is your server behind a proxy?

**Comment by e-im** [comment]
What other plugins do you have on the server? And is your client modded?

**Comment by e-im** [comment]
Very odd. I'm not really sure what could be causing this. None of those plugins would do it. As a last possible cause, how are you hosting the server? Are you using a service like Minehut (they specifically will cause this to not work, but others might as well)?
