### ISSUE TITLE
NCR Safe Server Status does not show on servers using velocity

### ISSUE THREAD

**Issue by Micim987** [e-im/FreedomChat#22]
With the plugin installed on both backend server the status shows as Unknown instead of Secure. The server also doesn't get the check mark in the server list. I am unsure if a separate velocity plugin is needed for if I need to enable some level of ping passthough.

Server is Velocity 2.1.2-201 with two backend servers both running petal (purpur fork) 1.19.2-"d448170" only chat plugin we are using is Venturechat. Le me know if you need more info

**Comment by e-im** [comment]
This is expected for the time being. A separate plugin running on Velocity would be needed.
