### ISSUE TITLE
FreedomChat 1.3.x won't disable on 1.19.2 and older.

### ISSUE THREAD

**Issue by Kichura** [e-im/FreedomChat#24]
FreedomChat in modrinth claims to be only compatible with 1.19.3 paper/purpur servers when using the 1.3.x version of it, However because it for some reason is still usable in older server versions; this will cause plugins like ViaVersion to [freak out and prevent players from logging in correctly.](https://github.com/ViaVersion/ViaBackwards/issues/508)

In this case, There should be a filtering system considered to prevent causing plugin breakage on older servers that way if possible and perhaps also alert players that craftbukkit/spigot is not supported and instead paper/purpur is recommended.

**Comment by e-im** [comment]
I had intentionally not added an artificial version limit, but this is no good. The last thing I want is to create annoying to debug issues for other plugins. Thanks for reporting this.

**Comment by e-im** [comment]
Resolved here https://github.com/e-im/FreedomChat/blob/b9ba6d7fc86c37b40d56b08c962a405b09226a58/src/main/java/ru/bk/oharass/freedomchat/FreedomChat.java#L15-L19

**Comment by Madis0** [comment]
> Resolved here
> 
> https://github.com/e-im/FreedomChat/blob/b9ba6d7fc86c37b40d56b08c962a405b09226a58/src/main/java/ru/bk/oharass/freedomchat/FreedomChat.java#L15-L19

You say it supports 761 but you check for 762?

**Comment by e-im** [comment]
That is unfortunate. Thanks for pointing it out. The check is correct, the text is wrong. protocol version 761 is for game version 1.19.3.
