### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by MagmaBro123** [e-im/FreedomChat#29]
Title. NCR says chat is still signed, meaning the plugin isn't working, see https://github.com/Aizistral-Studios/No-Chat-Reports/issues/402.

**Comment by e-im** [comment]
That isn't saying the chat is still signed, it's saying that the server rejected an unsigned message sent by the client. https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.4-Unified/src/main/java/com/aizistral/nochatreports/common/mixins/client/MixinChatListener.java#L43-L71

FreedomChat doesn't do anything to disable the server checking for signed messages.
If you would like the server to accept unsigned messages, disable `enforce-secure-profiles` in server.properties.

**Comment by Aizistral** [comment]
I'd argue that it would be a more user-friendly design to automatically turn `enforce-secure-profiles` off if user goes as far to install a plugin that, as they may think, should rid their server of any chat reporting stuff, of which enforcing message signing is one. I understand why you wouldn't want to go through the trouble of hacking vanilla to do that, but in that case I'd advise to clearly communicate that this is something the user still has to do separately, in readme/project page/etc.

**Comment by MagmaBro123** [comment]
I thought this worked without needing to do that until now.
