### ISSUE TITLE
Add a plugin to support all versions from 1.19.1 to 1.20.1

### ISSUE THREAD

**Issue by Gamer101233** [e-im/FreedomChat#33]
I think this could help a lot with the plugin by making the plugin and have 1 plugin file add support for all versions ranging from 1.19.1 to 1.20.1 so we dont whave to download all the different versions of the plugin and add them this feature would be nice so servers that support versions 1.20.1 and down dont have to have several plugins in the plugin file to block the report system this would be very nice so all we need to do is download 1 file then add it to our plugins and it blocks the chat singing and report buttons for all versions 1.20.1 down to 1.19.1.

If there is any confusion ill be here to answer.

**Comment by e-im** [comment]
Thanks for the feedback.

You only ever need one FreedomChat plugin installed at one time. The version listed is the native (no ViaVersion or ProtocolSupport/etc.) version of your server, not the client version. If you run a 1.20.1 server, you only need to install the 1.20.1 FreedomChat. The different versions are exclusively to account for changes in the server and will function regardless of client version.

It would be possible however to create a single jar which could work on all servers from 1.19.1-1.20.1, but I haven't done that. I might in the future, though.
